### PR TITLE
discussed with @aguaviva. it should work

### PR DESCRIPTION
**Pull request by sylvek**

### CODE REVIEW

**Comment by sylvek** [comment]
[app-release.apk.zip](https://github.com/sylvek/itracing2/files/5737420/app-release.apk.zip)

**Comment by aguaviva** [comment]
It crashes, I think the ".setChannelId(channelId)" is still there and that bit is SDK26 only.

**Comment by aguaviva** [comment]
Once I commented out that line all is working :)

**Comment by sylvek** [comment]
ok! thanks. 👍

**Comment by sylvek** [comment]
could you plz test this new apk?

[app-release.apk.zip](https://github.com/sylvek/itracing2/files/5739150/app-release.apk.zip)

**Comment by aguaviva** [comment]
All good! Just to double check I compiled the app from the source code and and the logcat looks ok. 👍

**Pull request merged**
